name: uptime-kuma
services:
  uptime-kuma:
    restart: always
    ports:
      - 3001:3001
    volumes:
      - /media/datatwo/uptime-kuma:/app/data
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
volumes:
  uptime-kuma:
    external: true
    name: uptime-kuma
